[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.virtualenv",
  "python310Packages.setuptools",
  "python310Packages.wheel",
  "zlib"  # Required for Python package builds
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv .venv",  # Create isolated virtual environment
  "source .venv/bin/activate",
  "pip install --no-cache-dir -U pip setuptools wheel",  # Safe upgrade within venv
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"