[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib.dev",
  "libffi.dev",
  "openssl.dev",
  "gcc",
  "libxml2.dev",
  "libxslt.dev",
  "stdenv.cc.cc.lib",
  "openblas",
  "lapack"
]

[phases.install]
commands = [
  # Clean environment
  "rm -rf .nixpacks",
  
  # Install core packages
  "cd backend",
  "python -m venv /app/venv --copies --without-pip",
  "source /app/venv/bin/activate",
  
  # Install pip manually
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py --no-cache-dir",
  
  # Set library paths
  "export LD_LIBRARY_PATH=$(nix-build --no-out-link -A stdenv.cc.cc.lib)/lib:$LD_LIBRARY_PATH",
  
  # Install numpy with OpenBLAS support
  "/app/venv/bin/pip install --no-cache-dir 'numpy==1.24.4' --only-binary=:all:",
  
  # Install remaining requirements
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath backend app:app"
