[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib.dev",
  "libffi.dev",
  "openssl.dev",
  "gcc",
  "libxml2.dev",
  "libxslt.dev",
  "stdenv.cc.cc.lib",
  "libjpeg",
  "freetype.dev",
  "libpng",
  "libcxx"
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv /app/venv --system-site-packages",
  "source /app/venv/bin/activate",
  "export C_INCLUDE_PATH=${pkgs.zlib.dev}/include:${pkgs.libffi.dev}/include",
  "export LIBRARY_PATH=${pkgs.zlib}/lib:${pkgs.libffi}/lib",
  "/app/venv/bin/pip install --no-cache-dir -U pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"