# nixpacks.toml
[phases.setup]
nixPkgs = [
    "stdenv",
    "python310",
    "python310Packages.virtualenv",
    "python310Packages.pip",
    "zlib.dev",
    "libffi.dev",
    "openssl.dev",
    "gcc",
    "glibc",
    "libstdc++",
    "stdenv.cc.cc.lib"
]

[phases.install]
cmds = [
    "python -m venv /app/venv",
    ". /app/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /app/venv/bin/activate && CFLAGS='-std=c99' CXXFLAGS='-std=c++11' pip install 'numpy==1.24.4'",
    ". /app/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
LIBRARY_PATH = "/lib:/usr/lib:/usr/local/lib"
LD_LIBRARY_PATH = "/lib:/usr/lib:/usr/local/lib"