[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib.dev",
  "libffi.dev",
  "openssl.dev",
  "gcc",
  "libxml2.dev",
  "libxslt.dev",
  "stdenv.cc.cc.lib",
  "openblas",
  "lapack",
  "libcxx"
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv /app/venv --system-site-packages",
  
  # Explicit compiler flags with exact Nix paths
  "export C_INCLUDE_PATH=$(nix-build --no-out-link -A zlib.dev)/include:$(nix-build --no-out-link -A libffi.dev)/include",
  "export LIBRARY_PATH=$(nix-build --no-out-link -A zlib)/lib:$(nix-build --no-out-link -A libffi)/lib",
  "export LD_LIBRARY_PATH=$(nix-build --no-out-link -A stdenv.cc.cc.lib)/lib",
  
  # Install packages sequentially
  "/app/venv/bin/pip install --no-cache-dir -U pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir numpy==1.24.4",  # Updated for compatibility
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"