[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib",
  "libffi",
  "openssl",
  "gcc",
  "libpq.dev",
  "libxml2",
  "libxslt",
  "libstdcxx5"
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv /app/venv --system-site-packages",
  "/app/venv/bin/pip install --no-cache-dir --upgrade pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"