[phases.setup]
nixPkgs = [
    "python310",
    "python310Packages.pip",
    "python310Packages.virtualenv",
    "zlib",
    "libffi",
    "openssl",
    "gcc12"  # Use GCC 12 (compatible with GLIBC 2.37)
]

[phases.install]
cmds = [
    "python3.10 -m venv /app/venv",
    ". /app/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /app/venv/bin/activate && pip install 'numpy<1.25'",
    ". /app/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/venv/lib/python3.10/site-packages"
LD_LIBRARY_PATH = "/nix/var/nix/profiles/default/lib:/usr/lib:/lib:/usr/local/lib"
LIBRARY_PATH = "/nix/var/nix/profiles/default/lib:/usr/lib:/lib:/usr/local/lib"
PYTHONDONTWRITEBYTECODE = "1"