[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip", 
  "python310Packages.setuptools",
  "python310Packages.wheel",
  "python310Packages.virtualenv"
]

[phases.install]
commands = [
  "cd backend",
  "python -m ensurepip --upgrade",  # Safer pip initialization
  "pip install --no-cache-dir -r requirements.txt"  # Bypass corrupted caches
]

[phases.start]
command = "gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"