[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
command = "gunicorn app:app"