# nixpacks.toml
[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "python39Packages.virtualenv",
    "zlib",
    "libffi",
    "openssl"
]

[phases.install]
cmds = [
    "python3.9 -m venv /app/venv",
    ". /app/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /app/venv/bin/activate && pip install 'numpy<1.25'",
    ". /app/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/venv/lib/python3.9/site-packages"
LD_LIBRARY_PATH = "/usr/lib:/lib:/usr/local/lib"
LIBRARY_PATH = "/usr/lib:/lib:/usr/local/lib"
PYTHONDONTWRITEBYTECODE = "1"