# nixpacks.toml
[phases.setup]
nixPkgs = [
    "gcc",
    "glibc",
    "python310",
    "python310Packages.pip",
    "python310Packages.virtualenv"
]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/venv/lib/python3.10/site-packages"
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib:/lib:/usr/local/lib"
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib:/lib:/usr/local/lib"
DEBIAN_FRONTEND = "noninteractive"