# nixpacks.toml
[phases.setup]
aptPkgs = [
    "libstdc++6",
    "build-essential",
    "python3-dev",
    "libpq-dev"
]

nixPkgs = [
    "gcc",
    "glibc",
    "libffi",
    "openssl",
    "python310",
    "python310Packages.pip",
    "python310Packages.virtualenv",
    "zlib"
]

[phases.install]
cmds = [
    "ldconfig",
    "python -m venv /app/venv",
    ". /app/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /app/venv/bin/activate && pip install 'numpy==1.24.4'",
    ". /app/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
PYTHONPATH = "/app/venv/lib/python3.10/site-packages"
LD_LIBRARY_PATH = "/usr/lib:/lib:/usr/local/lib"
LIBRARY_PATH = "/usr/lib:/lib:/usr/local/lib"