[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel",
  "zlib",
  "gcc",  # Essential compiler
  "libffi",
  "openssl",
  "libstdcxx5"  # C++ standard library
]

[phases.install]
commands = [
  "cd backend",
  # Skip virtualenv and use Nix-managed environment
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"