# nixpacks.toml
[phases.setup]
nixPkgs = [
    "python310",
    "python310Packages.virtualenv",
    "python310Packages.pip",
    "zlib.dev",
    "libffi.dev",
    "openssl.dev",
    "gcc",
    "libxml2.dev",
    "libxslt.dev",
    "stdenv.cc.cc.lib"
]

[phases.install]
cmds = [
    "ls -la",
    "ls -la backend/",
    "python -m venv /app/venv",
    "source /app/venv/bin/activate",
    ". /app/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /app/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && cd backend && /app/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"