[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib.dev",
  "libffi.dev",
  "openssl.dev",
  "gcc",
  "libxml2.dev",
  "libxslt.dev",
  "postgresql",  # Required for psycopg2 if used
  "stdenv.cc.cc.lib"  # Critical C++ library
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv /app/venv --system-site-packages",
  "/app/venv/bin/pip install --no-cache-dir -U pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"