[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "zlib.dev",
  "libffi.dev",
  "openssl.dev",
  "gcc",
  "libxml2.dev",
  "libxslt.dev",
  "stdenv.cc.cc.lib",
  "openblas",
  "lapack"
]

[phases.install]
commands = [
  "cd backend",
  "python -m venv /app/venv --system-site-packages",
  
  # Explicitly install core dependencies first
  "/app/venv/bin/pip install --no-cache-dir -U pip setuptools wheel",
  "/app/venv/bin/pip install --no-cache-dir numpy==1.24.4",
  
  # Install remaining requirements
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"