[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.gunicorn"]

[phases.install]
commands = [
  "cd backend",  # Change context to backend dir
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
command = "gunicorn --pythonpath backend app:app"  # Path from root