# nixpacks.toml
[phases.setup]
nixPkgs = [
    "python310",
    "python310Packages.virtualenv",
    "python310Packages.pip",
    "zlib.dev",
    "libffi.dev",
    "openssl.dev",
    "gcc",
    "libxml2.dev",
    "libxslt.dev",
    "stdenv.cc.cc.lib"
]

[phases.install]
workdir = "/app/backend"
cmds = [
    "python -m venv ../venv",
    "source ../venv/bin/activate",
    ". ../venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". ../venv/bin/activate && pip install -r requirements.txt"
]

[start]
workdir = "/app/backend"
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"