[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip"[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "python310Packages.pip",
  "zlib",
  "libffi",
  "openssl"
]

[phases.install]
commands = [
  "cd backend",
  # Create isolated virtual environment
  "python -m venv /app/venv --system-site-packages",
  # Install packages in venv
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
command = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT --pythonpath . app:app"